name: Release express-app

on:
  push:
    branches:
      - main
    paths:
      - 'express-app/**'
      - '.github/workflows/express-app.yml'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push express-app
        uses: docker/build-push-action@v2
        with:
          context: express-app
          file: express-app/Dockerfile
          push: true
          tags: tarunkumarm/express-app:latest
